# Configuração para deploy gradual
# A versão HTML atual funciona normalmente
# A versão React será configurada separadamente

# Fallback para a versão HTML atual (funcionando)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200