# Configuração para deploy gradual
# A versão HTML atual funciona normalmente

# Redirect específico para página de login React (versão real)
[[redirects]]
  from = "/login-react"
  to = "/login-react.html"
  status = 200

# Fallback para a versão HTML atual (funcionando)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200