# Configuração específica para a versão React
[build]
  command = "npm install && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Redirects para a versão React
[[redirects]]
  from = "/react/*"
  to = "/:splat"
  status = 200

# Fallback para index da versão React
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
